import type { ProjectListItem, ProjectCard } from './types'

export const PROJECT_LIST: ProjectListItem[] = [
  {
    id: 'diggo',
    name: 'DIGGO',
    type: '개인 프로젝트',
    period: '2026.03 — 2026.06',
    available: true,
  },
  {
    id: 'activio-v2',
    name: 'ACTIVIO v2',
    type: '팀 프로젝트',
    period: '2026.05 — 2026.06',
    available: true,
  },
  {
    id: 'activio-v1',
    name: 'ACTIVIO v1',
    type: '팀 프로젝트',
    period: '2026.04 — 2026.05',
    available: true,
  },
  {
    id: 'lions-study',
    name: '사자들의 공부방',
    type: '팀 프로젝트',
    period: '2026.02 — 2026.03',
    available: true,
  },
]

export const PROJECT_CARDS: ProjectCard[] = [
  {
    id: 'diggo',
    name: 'DIGGO',
    type: '개인 프로젝트',
    period: '2026.03 — 2026.06',
    available: true,
    thumbnail: '/images/diggo/hero_screenshot.png',
    cardStack: [
      'Next.js',
      'React.js',
      'TypeScript',
      'Tailwind CSS',
      'TanStack Query',
      'Zustand',
      'Supabase',
      'Vercel',
    ],
    deployUrl: 'https://diggo.vercel.app',
    githubUrl: 'https://github.com/smj123432-lab/diggo',
  },
  {
    id: 'activio-v2',
    name: 'ACTIVIO v2',
    type: '팀 프로젝트',
    period: '2026.05 — 2026.06',
    available: true,
    thumbnail: '/images/activio-v2/screenshot1.png',
    cardStack: [
      'Next.js',
      'TypeScript',
      'React.js',
      'Tailwind CSS',
      'Supabase',
      'Zustand',
      'TanStack Query',
      'Zod',
      'Vercel',
    ],
    deployUrl: 'https://activio-red.vercel.app',
    githubUrl: 'https://github.com/JMI-J/Activio',
  },
  {
    id: 'activio-v1',
    name: 'ACTIVIO v1',
    type: '팀 프로젝트',
    period: '2026.04 — 2026.05',
    available: true,
    thumbnail: '/images/activio-v1/screenshot1.png',
    cardStack: [
      'Next.js',
      'TypeScript',
      'React.js',
      'Tailwind CSS',
      'Supabase',
      'Zustand',
      'TanStack Query',
      'Zod',
      'Vercel',
    ],
    deployUrl: 'https://final-project-team3.vercel.app',
    githubUrl: 'https://github.com/FRONTENDBOOTCAMP-16th/final-project-team3',
  },
  {
    id: 'lions-study',
    name: '사자들의 공부방',
    type: '팀 프로젝트',
    period: '2026.02 — 2026.03',
    available: true,
    thumbnail: '/images/lions-study/hero_screenshot.png',
    cardStack: ['HTML', 'CSS / SCSS', 'JavaScript (ES6+)'],
    deployUrl: 'http://leedh9207.dothome.co.kr/',
    githubUrl: 'https://github.com/FRONTENDBOOTCAMP-16th/vanilla-project-team2',
  },
]
